apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-sync-group-0
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-only
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/gitops.git
        revision: master
        directories:
          - path: kubernetes/apps/cert-manager
          - path: kubernetes/apps/inter-device-manager
          - path: kubernetes/apps/longhorn-system
          - path: kubernetes/apps/metallb-system
          - path: kubernetes/apps/traefik
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
      annotations:
        argocd.argoproj.io/sync-wave: '0'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: https://github.com/vaisanenj/gitops.git
        path: '{{.path.path}}'
        targetRevision: master
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false