apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-system-setup
  namespace: argocd
spec:
  syncPolicy:
    automated:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - maxUpdate: 1
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/gitops.git
        revision: dev
        directories:
          - path: kubernetes/system/metallb-system
          - path: kubernetes/system/intel-device-manager
          - path: kubernetes/system/external-secrets
          - path: kubernetes/system/cert-manager
          - path: kubernetes/system/traefik
          - path: kubernetes/system/longhorn-system
          - path: kubernetes/system/kube-prometheus-stack
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: https://github.com/vaisanenj/gitops.git
        path: '{{.path.path}}'
        targetRevision: dev
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false