apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-sync-group-1
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-only
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/gitops.git
        revision: master
        directories:
          - path: kubernetes/apps/gameserver-enshrouded/overlay/*
          - path: kubernetes/apps/gameserver-satisfactory/overlay/*
          - path: kubernetes/apps/gameserver-valheim/overlay/*
  template:
    metadata:
      name: '{{index .path.segments 2}}-{{.path.basenameNormalized}}'
      annotations:
        argocd.argoproj.io/sync-wave: '1'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}-{{.path.basenameNormalized}}'
      source:
        repoURL: https://github.com/vaisanenj/gitops.git
        path: '{{.path.path}}'
        targetRevision: master
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false