apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-cluster-setup
  namespace: argocd
spec:
  syncPolicy:
    automated:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions: # First setup
          - key: app.kubernetes.io/instance
            operator: in
            values:
              - external-secrets
              - intel-device-manager
              - metallb-system
        - matchExpressions: # second setup
          - key: app.kubernetes.io/instance
            operator: in
            values:
              - cert-manager
        - matchExpressions: # third setup
          - key: app.kubernetes.io/instance
            operator: in
            values:
              - traefik
        - matchExpressions: # fourth setup
          - key: app.kubernetes.io/instance
            operator: in
            values:
              - longhorn
        - matchExpressions: # fifth setup
          - key: app.kubernetes.io/instance
            operator: in
            values:
              - openldap
              - kube-prometheus-stack
              - gitea
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/gitops.git
        revision: dev
        directories:
          - path: kubernetes/apps/metallb-system
          - path: kubernetes/apps/external-secrets
          - path: kubernetes/apps/intel-device-manager
          - path: kubernetes/apps/cert-manager
          - path: kubernetes/apps/traefik
          - path: kubernetes/apps/longhorn-system
          - path: kubernetes/apps/openldap
          - path: kubernetes/apps/gitea
          - path: kubernetes/apps/kube-prometheus-stack
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: https://github.com/vaisanenj/gitops.git
        path: '{{.path.path}}'
        targetRevision: dev
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false