apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb-system
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-only
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/gitops.git
        revision: master
        directories:
          - path: kubernetes/apps/metallb-system
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      destination:
        name: in-cluster
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: https://github.com/vaisanenj/gitops.git
        path: '{{.path.path}}'
        targetRevision: master
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false