apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-cluster-setup
  namespace: argocd
spec:
  syncPolicy:
    automated:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/gitops.git
        revision: dev
        directories:
          - path: kubernetes/apps/metallb-system
          - path: kubernetes/apps/external-secrets
          - path: kubernetes/apps/intel-device-manager
          - path: kubernetes/apps/cert-manager
          - path: kubernetes/apps/openldap
          - path: kubernetes/apps/traefik
          - path: kubernetes/apps/longhorn-system
          - path: kubernetes/apps/kube-prometheus-stack
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: https://github.com/vaisanenj/gitops.git
        path: '{{.path.path}}'
        targetRevision: dev
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false