apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-app
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-only
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/gitops.git
        revision: master
        directories:
          - path: kubernetes/apps/argocd
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{.path.basenameNormalized}}'
      annotations:
        argocd.argoproj.io/sync-wave: '0'
    spec:
      project: default
      destination:
        name: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}-{{.path.basenameNormalized}}'
      source:
        repoURL: in-cluster
        path: '{{.path.path}}'
        targetRevision: master
      syncPolicy:
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false