apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-sync-group-0
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-only
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: http://svc-gitea.gitea:3000/vaisajon/Kube-apps
        revision: HEAD
        directories:
          - path: kubernetes/apps/cert-manager
          - path: kubernetes/apps/intel-device-manager
          - path: kubernetes/apps/traefik
          - path: kubernetes/apps/metallb-system
          - path: kubernetes/apps/longhorn-system
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
      annotations:
        argocd.argoproj.io/sync-wave: '0'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: http://svc-gitea.gitea:3000/vaisajon/Kube-apps
        path: '{{.path.path}}'
        targetRevision: HEAD
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false