apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-app
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-only
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/gitops.git
        revision: master
        directories:
          - path: kubernetes/apps/argocd
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{.path.basenameNormalized}}'
      annotations:
        argocd.argoproj.io/sync-wave: '0'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ (split "/" .path.path)._3 }}'
      project: default
      source:
        repoURL: https://github.com/vaisanenj/gitops.git
        path: '{{index .path.segments 1}}-{{.path.basenameNormalized}}'
        targetRevision: master
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false