apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-cluster-setup
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-only
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/gitops.git
        revision: HEAD
        directories:
          - path: kubernetes/apps/*
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: cluster-setup
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: https://github.com/vaisanenj/gitops.git
        path: '{{.path.path}}'
        targetRevision: HEAD
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false