apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - argocd-ns.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.10/manifests/install.yaml
  - argo-sync-group-0.yaml
  - argo-sync-group-1.yaml