#ports:
#  local: 
#    port: 9443
#    expose: true
#    exposedPort: 8443

#ingressRoute:
#  dashboard:
#    enabled: true

#deployment:
#  additionalVolumes:
#    - name: plugins
#additionalVolumeMounts:
#  - name: plugins
#    mountPath: /plugins-storage
#additionalArguments:
#  - "--api"
#  - "--api.dashboard=true"
#  - "--api.insecure=true"
#  - "--experimental.plugins.blockpath.moduleName=github.com/traefik/plugin-blockpath"
#  - "--experimental.plugins.blockpath.version=v0.2.1"