traefik:
  deployment:
    additionalVolumes:
    - name: plugins
  additionalVolumeMounts:
  - name: plugins
    mountPath: /plugins-storage
  additionalArguments:
  - "--api"
  - "--api.dashboard=true"
  - "--api.insecure=true"
  - "--experimental.plugins.blockpath.moduleName=github.com/traefik/plugin-blockpath"
  - "--experimental.plugins.blockpath.version=v0.2.1"

  ports:
    web:
      expose:
        default: true
    websecure:
      expose:
        default: true
    private-web:
      port: 80
      expose:
        default: false
        internal: true
      exposedPort: 80
    private-websecure:
      port: 443
      expose:
        default: false
        internal: true
      exposedPort: 8443

  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`homelab.local`) && (PathPrefix(`/dashboard`)
      entryPoints: ['private-websecure']

  service:
    additionalServices:
      internal:
        type: LoadBalancer
        labels:
          traefik-service-label: internal