traefik:
  ports:
    traefik:
      expose:
        # Sensitive data should not be exposed on the internet
        # => Keep this disabled !
        default: false
        internal: true

  service:
    additionalServices:
      internal:
        type: ClusterIP
        labels:
          traefik-service-label: internal

#    dashboard:
#      enabled: true
#    ports:
#      local: 
#        port: 9443
#        expose: true
#        exposedPort: 8443
#    deployment:
#      additionalVolumes:
#      - name: plugins
#    additionalVolumeMounts:
#    - name: plugins
#      mountPath: /plugins-storage
#    additionalArguments:
#    - "--api"
#    - "--api.dashboard=true"
#    - "--api.insecure=true"
#    - "--experimental.plugins.blockpath.moduleName=github.com/traefik/plugin-blockpath"
#    - "--experimental.plugins.blockpath.version=v0.2.1"