apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-certificate
spec:
  acme:
    email: jonivaisanen@mail.com
    privateKeySecretRef:
      name: letsencrypt-prod.key.tls
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: traefik
      selector: {}