apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/vaisanenj/gitops.git
    revision: master
    path: kubernetes/argocd/*
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true