apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apm-certificate
  namespace: kube-promtheus-stack
spec:
  secretName: apm-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - apm.vaisanen.cloud