apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecrets
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: grafana-admin-credentials
  data:
  - secretKey: admin-user
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: grafana-admin-user
      key: kube-prometheus-stack
      metadataPolicy: None
  - secretKey: admin-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: grafana-admin-pass
      key: kube-prometheus-stack
      metadataPolicy: None