apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-certificate
  namespace: jellyfin
spec:
  secretName: jellyfin-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.vaisanen.cloud