apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phpldapadmin-certificate
  namespace: phpldapadmin-system
spec:
  secretName: phpldapadmin-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - phpldapadmin.vaisanen.cloud