apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openldap
resources:
  - statefulset.yaml
  - service.yaml
  - certificate.yaml
  - ingressRoute.yaml

labels:
  - includeSelectors: true
    pairs:
      application: openldap