apiVersion: apps/v1
kind: Statefulset
metadata:
  name: openldap
  namespace: openldap
spec:
  strategy:
    type: Recreate
  replicas: 1
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-openldap
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
  template:
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:latest
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: LDAP_ORGANISATION
              value: "Home Inc."
            - name: LDAP_DOMAIN
              value: vaisanen.cloud
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-passwords
                  key: admin
            - name: LDAP_READONLY_USER
              value: "true"
            - name: LDAP_READONLY_USERNAME
              value: readonly
            - name: LDAP_READONLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-passwords
                  key: readonly
          volumeMounts:
            - mountPath: /container/service/slapd/assets/certs
              subPath: certificates
              name: data
            - mountPath: /var/lib/ldap
              subPath: slapd/database
              name: data
            - mountPath: /etc/ldap/slapd.d
              subPath: slapd/config
              name: data
        - name: phpldapadmin
          image: osixia/phpldapadmin:latest
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: svc-openldap
            - name: PHPLDAPADMIN_HTTPS
              value: "false"