apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-certificate
  namespace: nextcloud
spec:
  secretName: nextcloud-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - nextcloud.vaisanen.cloud