apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: -1
namespace: intel-device-manager
resources:
  # Start NFD - if your cluster doesn't have NFD installed yet
  - 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd?ref=release-0.32'
  # Create NodeFeatureRules for detecting GPUs on nodes
  - 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref=release-0.32'
  # Create GPU plugin daemonset
  - 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/gpu_plugin/overlays/nfd_labeled_nodes?ref=release-0.32'