apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb
resources:
  - statefulSet.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      application: mariadb