apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  replicas: 2
  template:
    spec:
     terminationGracePeriodSeconds: 1800
     containers:
      - name: mariadb
        image: mariadb:10.7.8
        env:
        - name: TZ
          value: Europe/Helsinki
        - name: MYSQL_ROOT_PASSWORD
          value: changethis
        volumeMounts:
         - name: data
           mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn-rc-1
      resources:
        requests:
          storage: 1Gi
