apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-ingressroute
  annotations:
    spec.ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: private-web
spec:
  rules:
  - host: homelab.local
    http:
      paths:
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: api@internal
            port:
              number: 8080