apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  
commonAnnotations:
  application: mariadb
  managed-by: "kustomize"

labels:
  - includeSelectors: true
    pairs:
      application: mariadb