apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-certificate
  namespace: gitea
spec:
  secretName: gitea-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - gitea.vaisanen.cloud