apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-gitea
      containers:
        - name: gitea
          image: gitea/gitea:1.18.5
          resources:
            requests:
              cpu: "50m"
              memory: "512Mi"
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 200
            timeoutSeconds: 5
            periodSeconds: 10