apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
  - networkpolicies.yaml
  - ../../resources/mariadb
  
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: MARIADB_DATABASE
        value: gitea
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: MARIADB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: db-root-password
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: MARIADB_USER
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: db-user
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: MARIADB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: db-password
  target:
    kind: StatefulSet
    name: mariadb