apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-gitea
      containers:
        - name: gitea
          image: gitea/gitea:1.18.5
          resources:
            requests:
              cpu: "50m"
              memory: "512Mi"
          env:
            - name: LOCAL_ROOT_URL
              value: https://gitea.local
            - name: GITEA__database__DB_TYPE
              value: mysql
            - name: GITEA__database__HOST
              value: localhost:3306
            - name: GITEA__database__NAME
              value: gitea
            - name: GITEA__database__USER
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: db-user
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: db-password
          volumeMounts:
            - name: data
              subPath: app
              mountPath: /data
        - name: mariadb
          image: mariadb:11.7.2
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: MARIADB_DATABASE
              value: gitea
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: db-root-password
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: db-user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: db-password
          volumeMounts:
          - name: data
            subPath: database
            mountPath: /var/lib/mysql